// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrhKLK0AxUopA0ZHFrDvu_di_RAd2ZJnw',
    appId: '1:830553234357:web:ec9c6c819de1ee292ed7fc',
    messagingSenderId: '830553234357',
    projectId: 'urjumper',
    authDomain: 'urjumper.firebaseapp.com',
    storageBucket: 'urjumper.appspot.com',
    measurementId: 'G-6YFTZER3F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN33f4Ypck0sW-gzUuertCTXdLKtgYhRU',
    appId: '1:830553234357:android:02349385da57713c2ed7fc',
    messagingSenderId: '830553234357',
    projectId: 'urjumper',
    storageBucket: 'urjumper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbczgjJSwi_0fyL1Idcut-2sFTq-VZF6c',
    appId: '1:830553234357:ios:39c3987eae17af282ed7fc',
    messagingSenderId: '830553234357',
    projectId: 'urjumper',
    storageBucket: 'urjumper.appspot.com',
    iosBundleId: 'com.myapp.urjumper',
  );
}
